META_FILE = 'db_meta.json'
DATA_DIR = 'data'
TABLE_FILE_EXTENSION = '.json'
ENCODING = 'utf-8'
READ_MODE = 'r'
WRITE_MODE = 'w'

INT = 'int'
STR = 'str'
BOOL = 'bool'
VALID_TYPES = {INT, STR, BOOL}
COLUMN_ID_NAME = 'ID'
COLUMN_SEPARATOR = ':'
COLUMN_LIST_SEPARATOR = ', '
COLUMN_SEPARATORS_IN_DEFINITION = 1
TABLE_LIST_MARK = '-'
EMPTY_TABLE_MAX_ID = 0
ID_INCREMENT = 1
DROP_TABLE_ACTION = 'удаление таблицы'
DELETE_DATA_ACTION = 'удаление данных из таблицы'

COMMAND_PROMPT = 'Введите команду: '
TABLE_NAME_ARG_COUNT = 1
ID_LIST_SEPARATOR = ','
CACHE_KEY_TABLE = 'table'
CACHE_KEY_WHERE = 'where'
CACHE_KEY_DATA = 'data'

CMD_EXIT = 'exit'
CMD_HELP = 'help'
CMD_CREATE_TABLE = 'create_table'
CMD_LIST_TABLES = 'list_tables'
CMD_DROP_TABLE = 'drop_table'
CMD_INSERT = 'insert'
CMD_SELECT = 'select'
CMD_UPDATE = 'update'
CMD_DELETE = 'delete'
CMD_INFO = 'info'

KW_INTO = 'into'
KW_VALUES = 'values'
KW_FROM = 'from'
KW_WHERE = 'where'
KW_SET = 'set'
TOKEN_EQUALS = '='
TOKEN_COMMA = ','
TOKEN_OPEN_PAREN = '('
TOKEN_CLOSE_PAREN = ')'
TRUE_LITERAL = 'true'
FALSE_LITERAL = 'false'
PUNCTUATION_CHARS = (
    f'{TOKEN_OPEN_PAREN}{TOKEN_CLOSE_PAREN}{TOKEN_COMMA}{TOKEN_EQUALS}'
)

INSERT_PREFIX_LENGTH = 3
VALUES_WRAPPER_LENGTH = 2
FROM_CLAUSE_LENGTH = 2
TABLE_NAME_LENGTH = 1
SET_CLAUSE_LENGTH = 4
WHERE_CLAUSE_LENGTH = 4
UPDATE_TOKEN_COUNT = TABLE_NAME_LENGTH + SET_CLAUSE_LENGTH + WHERE_CLAUSE_LENGTH
DELETE_TOKEN_COUNT = FROM_CLAUSE_LENGTH + WHERE_CLAUSE_LENGTH

CONFIRM_YES = 'y'
CONFIRM_NO = 'n'
ELAPSED_PRECISION = 3
